name: Build Artifacts

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Create artifacts
      run: |
        ./gradlew pack
        ./gradlew android:assembleDebug --stacktrace
        mv android/build/outputs/apk/debug/android-debug.apk android/build/outputs/apk/debug/Mindustry-CE-Android-${RELEASE_VERSION}.apk

    - name: Upload Android artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        file: android/build/outputs/apk/debug/Mindustry-CE-Android-${{ env.RELEASE_VERSION }}.apk
        tag: ${{ github.ref }}
