name: Sprite Packing

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Create Sprite Packing
      run: |
        ./gradlew tools:pack
    
    - name: Compress Sprite Folder
      run: |
        zip -r sprites-assets.zip core/assets/sprites

    - name: Upload Sprite Pack
      uses: svenstaro/upload-release-action@v2
      with:
        file: sprites-assets.zip
        repo_token: ${{ secrets.GITHUB_TOKEN }}
